# Mongo config
MONGODB_DATABASE: userMongo_1_1

# Database config
DB_NAME: user_1_1
DB_INITIAL_SIZE: 10
DB_MAX_ACTIVE: 100
DB_MIN_IDLE: 10
DB_MAX_IDLE: 100

# Log config
LOG_PATH: target

# Graylog config
GRAYLOG_FACILITY: BatchRelease

# config tomcat
TOMCAT_ACCESS_LOG_DIRECTORY: target

# Xslt config
XSLT_TRANSFORMATION_LOG_PATH: target

#Bath steps config
BATCH_MODE: queing
BATCH_FULL_ENABLED: true
BATCH_PAGE_SIZE: 50
THREAD_POOL_SIZE: 5
BATCH_CHUNK_SIZE: 50
BATCH_RUN_ON_STARTUP: false
BATCH_SKIP: 0

# Cron config
BATCH_LINK_RESOLUTION_CRON: "00 23 * * * *"

# Async config
ASYNC_THREAD_POOL_SIZE: 5
