# Mongo db config
MONGODB_DATABASE: userMongo_1_1

# Database config
DB_NAME: user_1_1
DB_INITIAL_SIZE: 10
DB_MAX_ACTIVE: 100
DB_MIN_IDLE: 10
DB_MAX_IDLE: 100

# Log config
LOG_PATH: target

# Graylog config
GRAYLOG_FACILITY: AsyncRelease

#  Tomcat config
TOMCAT_ACCESS_LOG_DIRECTORY: target

# Xslt config
XSLT_TRANSFORMATION_LOG_PATH: target

#POST-SAVE specific properties
CONCURRENT_CONSUMERS: 5

#MEDIA
EDITOR_MEDIA_COLLECTION: editor.files
METADATA_MEDIA_COLLECTION: media.files
TARGET_DIRECTORY_PATH: C:/dev/media-export

# Xml publish config
XML_PUBLISH_PATH: /flash-dev-1_1
XML_PUBLISH_CURRENT_COLLECTION: INTEG-CURRENT
XML_PUBLISH_VALID_COLLECTION: INTEG-VALID
XML_PUBLISH_MEDIA_COLLECTION: INTEG-MEDIA

#XML files upload
XML_UPLOAD_SOURCE_DIRECTORY_PATH: C:/dev/xml-import/to-process
XML_UPLOAD_TARGET_DIRECTORY_PATH: C:/dev/xml-import/done

# xml Export config
XML_EXPORT_TARGET_DIRECTORY_PATH: C:/dev/xml-export

# Async config
ASYNC_THREAD_POOL_SIZE: 5
