# Log config
LOG_PATH: target

# Graylog config
GRAYLOG_FACILITY: ErmRelease

# config tomcat
TOMCAT_ACCESS_LOG_DIRECTORY: target

# Xslt config
XSLT_TRANSFORMATION_LOG_PATH: target

# Database config
DB_SERVER_HOST: localhost
DB_NAME: erm_1_1
DB_INITIAL_SIZE: 10
DB_MAX_ACTIVE: 100
DB_MIN_IDLE: 10
DB_MAX_IDLE: 100

#ERM
ERM_PATH: C:/dev/els/resources_1_1
THREAD_POOL_SIZE: 10
TRANSFORMER_POOL_SIZE: 2
LOAD_TRANSFORMER: false

# Xslt config
XSLT_LOG_PATH: target

# Erm signature
ERM_SIGNATURE_DISPLAY_MODE: HIDE
