# Log config
LOG_PATH: /var/log/xmlfirst/recette4

# Graylog config
GRAYLOG_FACILITY: ErmRecette4

# config tomcat
TOMCAT_ACCESS_LOG_DIRECTORY: /var/log/xmlfirst/recette4/tomcat

# Xslt config
XSLT_TRANSFORMATION_LOG_PATH: /var/flash/generateXML/recette4

# Database config
DB_SERVER_HOST: 10.16.14.88
DB_NAME: erm-recette4
DB_INITIAL_SIZE: 10
DB_MAX_ACTIVE: 100
DB_MIN_IDLE: 10
DB_MAX_IDLE: 100

#ERM
ERM_PATH: /opt/REC4/flash/erm/hot-deploy
THREAD_POOL_SIZE: 12
TRANSFORMER_POOL_SIZE: 12
LOAD_TRANSFORMER: false

# Xslt config
XSLT_LOG_PATH: /tmp/log/recette4

# Erm signature
ERM_SIGNATURE_DISPLAY_MODE: DISPLAY
