# Mongo db config
MONGODB_DATABASE: userMongo_1_1

# Database config
DB_NAME: user_1_1
DB_INITIAL_SIZE: 10
DB_MAX_ACTIVE: 100
DB_MIN_IDLE: 10
DB_MAX_IDLE: 100

# Xml export
EXPORT_CONFIG_PATH: target
EXPORTED_XML_PATH: target

# Xslt config
XSLT_TRANSFORMATION_LOG_PATH: target

# Search interfacte template config
DEFAULT_TIR_PAGINATION_LIMIT: 50

#PUBLISH / PROOF
PUBLISH_API_URL: http://10.16.14.41:8080/xd-prio/api/treatExecutionOrder
PUBLISH_USER: user
PUBLISH_PWD: admin_xd_prio
PROOF_API_URL: http://10.16.14.41:8080/xd-prio/api/treatExecutionOrder
PROOF_USER: user
PROOF_PWD: admin_xd_prio
PUBLISH_PROOF_ENV: integ
# Max size for each file of metadata MEDIA by MB
MEDIA_METADATA_MAX_SIZE: 1

#Editor
EDITOR_CONFIG_DIRECTORY: "C:/temp/editor/configurations/"
EDITOR_SVG_SERVER_AUTO_DURATION: 30000000
EDITOR_SVG_CLIENT_AUTO_DURATION: 10000
PROLEXIS_API_PREFIX: api/prolexisws

#Media manager
MEDIA_MINIATURE_HEIGHT: 100
MEDIA_MINIATURE_WIDTH: 100

# Graylog config
GRAYLOG_FACILITY: EcmCoreRelease

# Log config
LOG_PATH: target


#security properties
SECURITY_SECRET: db2a2634cbae7c01ea2d22797deb11da


#validation
VALIDATION_TARGETS_NUMBER_LIMIT: 5

# Swagger config
SWAGGER_TOKEN_HEADER: false

# Monitoring config
MONITORING_DEBUG: false
MONITORING_SCORE: true

# Async config
ASYNC_THREAD_POOL_SIZE: 5

# Export config
EXPORT_PATH: target