# Env config
ENV: recette
ECM_VERSION: 1.1 Version 2

# Database config
DB_SERVER_HOST: 10.16.14.9
DB_SERVER_PORT: 3306
DB_USER: mariadb
DB_PWD: mariadb

# Log config
LOG_CONFIG: classpath:logback-spring.xml
LOG_LEVEL: DEBUG
LOG_APPENDERS: ASYNC,GRAYLOG
LOG_MAX_FILE_SIZE: 5MB
LOG_MAX_HISTORY: 50
LOG_TOTAL_SIZE_CAP: 5MB

# Graylog config
GRAYLOG_SERVER_HOST: 10.16.14.82
GRAYLOG_SERVER_PORT: 12212
GRAYLOG_MAXIMUM_MESSAGE_SIZE: 8192

# Security config
SECURITY_TIME_TO_LIVE_IN_DAYS: 31
SECURITY_TOKEN_VALIDITY_SEC: 1800

# Ref names config
REF_NAME_LIST: ALL_EBX_REFS


# Ldap server config
# Ldap config
LDAP_ENABLED: true
LDAP_SERVER_HOST: 10.16.23.2
LDAP_SERVER_PORT: 389
LDAP_USER: svc-els-xmlfirstad01@eu.els.local
LDAP_PWD: 4Su9xNa3

# tomcat config
TOMCAT_ACCESS_LOG_ENABLED: false

# Mongo config
MONGODB_SERVER_URL: 10.16.14.6:27017/?maxPoolSize=400&
MONGODB_PAGE_SIZE:  50
MONGODB_REMOVE_CHUNKS_SIZE: 1000

# HazelCast config
HAZELCAST_SERVER_HOST: 10.16.14.7
HAZELCAST_SERVER_PORT: 8181
HAZELCAST_DATABASE: recette1-ecm
HAZELCAST_EXEC_TIMEOUT_SEC: 2
HAZELCAST_GROUP_NAME: ecm
HAZELCAST_GROUP_PWD: flash

# Spring boot rabbitmq config
RABBIT_MQ_SERVER_HOST: 10.16.14.7
RABBIT_MQ_SERVER_PORT: 5672
RABBIT_MQ_USER: flash
RABBIT_MQ_PWD: flash
RABBIT_MQ_REST_API_URL: http://10.16.14.7:15672/api
RABBIT_MQ_NB_MESSAGES_LIMIT: 500

# Solr config
IS_SHARDED_SOLR: false
ZOOK_SERVER_URL:
SOLR_SERVER_URL: 10.16.14.8:8983
SOLR_CORE: flash

# Xml export config
XML_IMPORT_DEFAULT_CREATOR_LOGIN: slequime

# Spring boot mail config
MAIL_SERVER_HOST: FR000-SMTP001
MAIL_SERVER_PORT: 25
MAIL_USER:
MAIL_PWD:

# Feign config
FEIGN_CALL_TIMEOUT: 60000

# MarkLogic config
MARKLOGIC_SERVER_HOST: fr000-tstdb009
MARKLOGIC_SERVER_PORT: 8003
MARKLOGIC_USER: flash-rest-writer
MARKLOGIC_PWD: flash

# Media api config (RestHeart)
MEDIA_API_USER: admin
MEDIA_API_PWD: changeit
MEDIA_API_HOST: 10.16.14.6
MEDIA_API_PORT: 8081
MEDIA_API_PROTOCOL: http
MEDIA_DATABASE: recette1-ecm


#ASYNC
ASYNC_ENABLED: true
ASYNC_TIME_WAITING: 50

# HYSTRIX config
HYSTRIX_MAX_CONCURRENT_REQUESTS: 10000


# Ecm core server config
CORE_APP_SERVER_HOST: 10.16.14.5
CORE_APP_SERVER_PORT: 8080
CORE_APP_SERVER_CONTEXT_PATH: ecm-core

# Cache server config
CACHE_APP_SERVER_HOST: 10.16.14.7
CACHE_APP_SERVER_PORT: 8989
CACHE_APP_SERVER_CONTEXT_PATH: hazelcast
CACHE_APP_USER: user
CACHE_APP_PWD: hazel_server_admin

# Async server config
ASYNC_APP_SERVER_HOST: 10.16.14.4
ASYNC_APP_SERVER_PORT: 9190

# Erm server config
ERM_APP_SERVER_HOST: 10.16.14.4
ERM_APP_SERVER_PORT: 8091

# Admin server config
ADMIN_APP_SERVER_HOST: 10.16.14.5
ADMIN_APP_SERVER_PORT: 8080
ADMIN_APP_SERVER_CONTEXT_PATH: xfadmin

# batch server config
BATCH_APP_SERVER_HOST: 10.16.14.4
BATCH_APP_SERVER_PORT: 9191



# Notifications config
NOTIFICATION_TREATEMENT_CHUNK_SIZE: 100


#indexation
INDEX_HTML_PREVIEW: true


# multipart config
MULTIPART_MAX_REQUEST_SIZE: -1
MULTIPART_MAX_FILE_SIZE: -1


