# Mongo config
MONGODB_DATABASE: flash

# Database config
DB_NAME: flash
DB_INITIAL_SIZE: 10
DB_MAX_ACTIVE: 100
DB_MIN_IDLE: 10
DB_MAX_IDLE: 100

# Log config
LOG_PATH: /Async/Logs/batch

# Graylog config
GRAYLOG_FACILITY: BatchPreprod

# config tomcat
TOMCAT_ACCESS_LOG_DIRECTORY: /Async/Logs/batch/tomcat

# Xslt config
XSLT_TRANSFORMATION_LOG_PATH: file:/Async/flash/xsl

#Bath steps config
BATCH_MODE: queing
BATCH_FULL_ENABLED: true
BATCH_PAGE_SIZE: 400
THREAD_POOL_SIZE: 4
BATCH_CHUNK_SIZE: 100
BATCH_RUN_ON_STARTUP: false
BATCH_SKIP: -1

# Cron config
BATCH_LINK_RESOLUTION_CRON: "00 23 * * * *"

# Async config
ASYNC_THREAD_POOL_SIZE: 5
